In [124]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.model_selection import train_test_split

import torchvision as tv

import os
import numpy as np
import matplotlib.pyplot as plt
from tqdm.autonotebook import tqdm

from torch.cuda.amp import autocast, GradScaler
import plotly.graph_objects as go
import seaborn as sns
import plotly.express as px
import pandas as pd

In [125]:
X_array =  np.load('X_array.npy')
Y_array =  np.load('Y_array.npy')


In [126]:
X_train, X_test, y_train, y_test = train_test_split(X_array, Y_array, test_size=0.2, random_state=898)

In [127]:
X_train = torch.tensor(X_train)
y_train = torch.tensor(y_train)
X_test = torch.tensor(X_test)
y_test = torch.tensor(y_test)

In [128]:
print(len(X_train))
print(len(y_train))
print(len(X_test))
print(len(y_test))

359
359
90
90


In [129]:
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]

In [130]:
# Создаем Dataset и DataLoader
dataset_train = CustomDataset(X_train, y_train)
dataset_test = CustomDataset(X_test, y_test)
dataloader_train = torch.utils.data.DataLoader(dataset_train, batch_size=5, shuffle=True)
dataloader_test = torch.utils.data.DataLoader(dataset_test, batch_size=5, shuffle=False)

In [131]:
class ConvNet(nn.Module):
    def __init__(self):
        super(ConvNet, self).__init__()
        # Определение сверточных слоев
        self.conv1 = nn.Conv2d(1, 16, kernel_size=4, stride=1, padding=1)
        self.conv2 = nn.Conv2d(16, 32, kernel_size=3, stride=1, padding=1)
        #self.conv3 = nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1)
        # Определение пулинга
        self.pool = nn.MaxPool2d(kernel_size=3, stride=2, padding=0)
        # Определение полносвязных слоев
        self.fc1 = nn.Linear(32*24*10, 128)  # 128 каналов, 32x25 после применения пулинга
        self.fc2 = nn.Linear(128, 10)  # 10 классов

    def forward(self, x):
        # Пропускание данных через сверточные слои и функции активации
        x = self.pool(F.leaky_relu(self.conv1(x)))
        x = self.pool(F.leaky_relu(self.conv2(x)))
        #x = self.pool(F.leaky_relu(self.conv3(x)))
    
        # Выпрямление данных перед подачей на полносвязный слой
        x = x.view(-1, 32*24*10)  # Выпрямляем тензор
        x = F.leaky_relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Создание экземпляра нейронной сети
net = ConvNet()
# Печать архитектуры нейронной сети
print(net)

ConvNet(
  (conv1): Conv2d(1, 16, kernel_size=(4, 4), stride=(1, 1), padding=(1, 1))
  (conv2): Conv2d(16, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (pool): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  (fc1): Linear(in_features=7680, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=10, bias=True)
)


In [132]:
for param in net.parameters():
    param.data = param.data.double()

In [133]:
loss_fn = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(net.parameters(), lr=0.0001, betas=(0.9, 0.999))
scheduler = torch.optim.lr_scheduler.ExponentialLR(
    optimizer,
    gamma = 0.6
)

In [134]:
def accuracy(pred, label, threshold=0.5):
    pred = torch.sigmoid(pred)
    pred_labels = (pred > threshold).float()  # Threshold the predictions
    correct = (pred_labels == label).sum().item()  # Compare predictions with labels
    total = label.size(0) * label.size(1)  # Total number of labels
    return correct / total


In [135]:
device = 'cuda' # if torch.cuda.is_available() else 'cpu'
model = net.to(device)
loss_fn = loss_fn.to(device)

In [136]:
use_amp = True
scaler = torch.cuda.amp.GradScaler()
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False

In [137]:
epochs = 100

for epoch in range(epochs):
    loss_val = 0.0
    acc_val = 0.0
    for sample in tqdm(dataloader_train):
        matrix, label = sample[0].to(device), sample[1].to(device)
        optimizer.zero_grad()

        # Добавим измерение каналов к данным
        matrix = matrix.unsqueeze(1)
  
        with autocast(use_amp):
            pred = model(matrix)
            loss = loss_fn(pred, label.float())

        scaler.scale(loss).backward()
        loss_item = loss.item()
        loss_val += loss_item

        scaler.step(optimizer)
        scaler.update()

        acc_current = accuracy(pred.cpu().float(), label.cpu().float())
        acc_val += acc_current

    print(f'Epoch: [{epoch+1}/{epochs}], Loss: {loss_val/len(dataloader_train):.5f}, Accuracy: {acc_val/len(dataloader_train):.3f}')

100%|██████████| 72/72 [00:00<00:00, 92.27it/s] 


Epoch: [1/100], Loss: 0.74712, Accuracy: 0.701


100%|██████████| 72/72 [00:00<00:00, 151.68it/s]


Epoch: [2/100], Loss: 0.57961, Accuracy: 0.770


100%|██████████| 72/72 [00:00<00:00, 149.33it/s]


Epoch: [3/100], Loss: 0.54929, Accuracy: 0.775


100%|██████████| 72/72 [00:00<00:00, 159.87it/s]


Epoch: [4/100], Loss: 0.51380, Accuracy: 0.779


100%|██████████| 72/72 [00:00<00:00, 160.10it/s]


Epoch: [5/100], Loss: 0.49774, Accuracy: 0.793


100%|██████████| 72/72 [00:00<00:00, 158.78it/s]


Epoch: [6/100], Loss: 0.45825, Accuracy: 0.797


100%|██████████| 72/72 [00:00<00:00, 159.19it/s]


Epoch: [7/100], Loss: 0.44518, Accuracy: 0.805


100%|██████████| 72/72 [00:00<00:00, 162.16it/s]


Epoch: [8/100], Loss: 0.44093, Accuracy: 0.807


100%|██████████| 72/72 [00:00<00:00, 161.42it/s]


Epoch: [9/100], Loss: 0.42290, Accuracy: 0.808


100%|██████████| 72/72 [00:00<00:00, 160.78it/s]


Epoch: [10/100], Loss: 0.42517, Accuracy: 0.810


100%|██████████| 72/72 [00:00<00:00, 160.81it/s]


Epoch: [11/100], Loss: 0.43237, Accuracy: 0.815


100%|██████████| 72/72 [00:00<00:00, 160.49it/s]


Epoch: [12/100], Loss: 0.41963, Accuracy: 0.815


100%|██████████| 72/72 [00:00<00:00, 162.96it/s]


Epoch: [13/100], Loss: 0.40987, Accuracy: 0.819


100%|██████████| 72/72 [00:00<00:00, 156.07it/s]


Epoch: [14/100], Loss: 0.40866, Accuracy: 0.817


100%|██████████| 72/72 [00:00<00:00, 162.00it/s]


Epoch: [15/100], Loss: 0.39913, Accuracy: 0.826


100%|██████████| 72/72 [00:00<00:00, 161.43it/s]


Epoch: [16/100], Loss: 0.39841, Accuracy: 0.824


100%|██████████| 72/72 [00:00<00:00, 160.71it/s]


Epoch: [17/100], Loss: 0.39326, Accuracy: 0.826


100%|██████████| 72/72 [00:00<00:00, 162.53it/s]


Epoch: [18/100], Loss: 0.39517, Accuracy: 0.823


100%|██████████| 72/72 [00:00<00:00, 160.35it/s]


Epoch: [19/100], Loss: 0.38770, Accuracy: 0.828


100%|██████████| 72/72 [00:00<00:00, 152.78it/s]


Epoch: [20/100], Loss: 0.38474, Accuracy: 0.830


100%|██████████| 72/72 [00:00<00:00, 150.84it/s]


Epoch: [21/100], Loss: 0.38416, Accuracy: 0.830


100%|██████████| 72/72 [00:00<00:00, 154.30it/s]


Epoch: [22/100], Loss: 0.37783, Accuracy: 0.832


100%|██████████| 72/72 [00:00<00:00, 156.39it/s]


Epoch: [23/100], Loss: 0.37521, Accuracy: 0.835


100%|██████████| 72/72 [00:00<00:00, 156.17it/s]


Epoch: [24/100], Loss: 0.37464, Accuracy: 0.830


100%|██████████| 72/72 [00:00<00:00, 159.51it/s]


Epoch: [25/100], Loss: 0.37316, Accuracy: 0.835


100%|██████████| 72/72 [00:00<00:00, 151.82it/s]


Epoch: [26/100], Loss: 0.37104, Accuracy: 0.834


100%|██████████| 72/72 [00:00<00:00, 156.15it/s]


Epoch: [27/100], Loss: 0.37085, Accuracy: 0.838


100%|██████████| 72/72 [00:00<00:00, 158.57it/s]


Epoch: [28/100], Loss: 0.38085, Accuracy: 0.830


100%|██████████| 72/72 [00:00<00:00, 156.03it/s]


Epoch: [29/100], Loss: 0.37118, Accuracy: 0.833


100%|██████████| 72/72 [00:00<00:00, 160.42it/s]


Epoch: [30/100], Loss: 0.36269, Accuracy: 0.836


100%|██████████| 72/72 [00:00<00:00, 162.39it/s]


Epoch: [31/100], Loss: 0.36326, Accuracy: 0.835


100%|██████████| 72/72 [00:00<00:00, 161.80it/s]


Epoch: [32/100], Loss: 0.35755, Accuracy: 0.843


100%|██████████| 72/72 [00:00<00:00, 155.29it/s]


Epoch: [33/100], Loss: 0.35663, Accuracy: 0.838


100%|██████████| 72/72 [00:00<00:00, 162.71it/s]


Epoch: [34/100], Loss: 0.35142, Accuracy: 0.845


100%|██████████| 72/72 [00:00<00:00, 161.41it/s]


Epoch: [35/100], Loss: 0.35416, Accuracy: 0.845


100%|██████████| 72/72 [00:00<00:00, 161.32it/s]


Epoch: [36/100], Loss: 0.34824, Accuracy: 0.844


100%|██████████| 72/72 [00:00<00:00, 152.58it/s]


Epoch: [37/100], Loss: 0.35676, Accuracy: 0.843


100%|██████████| 72/72 [00:00<00:00, 158.94it/s]


Epoch: [38/100], Loss: 0.34470, Accuracy: 0.848


100%|██████████| 72/72 [00:00<00:00, 157.93it/s]


Epoch: [39/100], Loss: 0.34647, Accuracy: 0.849


100%|██████████| 72/72 [00:00<00:00, 147.72it/s]


Epoch: [40/100], Loss: 0.34041, Accuracy: 0.846


100%|██████████| 72/72 [00:00<00:00, 154.84it/s]


Epoch: [41/100], Loss: 0.33865, Accuracy: 0.851


100%|██████████| 72/72 [00:00<00:00, 154.14it/s]


Epoch: [42/100], Loss: 0.33609, Accuracy: 0.846


100%|██████████| 72/72 [00:00<00:00, 156.46it/s]


Epoch: [43/100], Loss: 0.33592, Accuracy: 0.848


100%|██████████| 72/72 [00:00<00:00, 158.93it/s]


Epoch: [44/100], Loss: 0.33349, Accuracy: 0.849


100%|██████████| 72/72 [00:00<00:00, 160.98it/s]


Epoch: [45/100], Loss: 0.32612, Accuracy: 0.852


100%|██████████| 72/72 [00:00<00:00, 157.69it/s]


Epoch: [46/100], Loss: 0.32552, Accuracy: 0.857


100%|██████████| 72/72 [00:00<00:00, 151.10it/s]


Epoch: [47/100], Loss: 0.35024, Accuracy: 0.848


100%|██████████| 72/72 [00:00<00:00, 157.80it/s]


Epoch: [48/100], Loss: 0.33890, Accuracy: 0.850


100%|██████████| 72/72 [00:00<00:00, 149.36it/s]


Epoch: [49/100], Loss: 0.32420, Accuracy: 0.857


100%|██████████| 72/72 [00:00<00:00, 144.07it/s]


Epoch: [50/100], Loss: 0.32486, Accuracy: 0.852


100%|██████████| 72/72 [00:00<00:00, 150.42it/s]


Epoch: [51/100], Loss: 0.31989, Accuracy: 0.858


100%|██████████| 72/72 [00:00<00:00, 150.02it/s]


Epoch: [52/100], Loss: 0.31897, Accuracy: 0.854


100%|██████████| 72/72 [00:00<00:00, 147.32it/s]


Epoch: [53/100], Loss: 0.31800, Accuracy: 0.862


100%|██████████| 72/72 [00:00<00:00, 149.18it/s]


Epoch: [54/100], Loss: 0.31516, Accuracy: 0.861


100%|██████████| 72/72 [00:00<00:00, 151.34it/s]


Epoch: [55/100], Loss: 0.31411, Accuracy: 0.861


100%|██████████| 72/72 [00:00<00:00, 153.45it/s]


Epoch: [56/100], Loss: 0.31954, Accuracy: 0.856


100%|██████████| 72/72 [00:00<00:00, 156.36it/s]


Epoch: [57/100], Loss: 0.31447, Accuracy: 0.858


100%|██████████| 72/72 [00:00<00:00, 155.77it/s]


Epoch: [58/100], Loss: 0.31200, Accuracy: 0.864


100%|██████████| 72/72 [00:00<00:00, 148.18it/s]


Epoch: [59/100], Loss: 0.30726, Accuracy: 0.863


100%|██████████| 72/72 [00:00<00:00, 155.67it/s]


Epoch: [60/100], Loss: 0.30593, Accuracy: 0.864


100%|██████████| 72/72 [00:00<00:00, 156.33it/s]


Epoch: [61/100], Loss: 0.30835, Accuracy: 0.865


100%|██████████| 72/72 [00:00<00:00, 156.63it/s]


Epoch: [62/100], Loss: 0.30396, Accuracy: 0.864


100%|██████████| 72/72 [00:00<00:00, 151.71it/s]


Epoch: [63/100], Loss: 0.29706, Accuracy: 0.866


100%|██████████| 72/72 [00:00<00:00, 150.88it/s]


Epoch: [64/100], Loss: 0.29652, Accuracy: 0.865


100%|██████████| 72/72 [00:00<00:00, 151.93it/s]


Epoch: [65/100], Loss: 0.29622, Accuracy: 0.868


100%|██████████| 72/72 [00:00<00:00, 151.75it/s]


Epoch: [66/100], Loss: 0.29560, Accuracy: 0.868


100%|██████████| 72/72 [00:00<00:00, 156.38it/s]


Epoch: [67/100], Loss: 0.30108, Accuracy: 0.866


100%|██████████| 72/72 [00:00<00:00, 149.22it/s]


Epoch: [68/100], Loss: 0.29543, Accuracy: 0.869


100%|██████████| 72/72 [00:00<00:00, 155.13it/s]


Epoch: [69/100], Loss: 0.28817, Accuracy: 0.875


100%|██████████| 72/72 [00:00<00:00, 145.51it/s]


Epoch: [70/100], Loss: 0.29217, Accuracy: 0.871


100%|██████████| 72/72 [00:00<00:00, 148.28it/s]


Epoch: [71/100], Loss: 0.29389, Accuracy: 0.868


100%|██████████| 72/72 [00:00<00:00, 152.05it/s]


Epoch: [72/100], Loss: 0.28838, Accuracy: 0.876


100%|██████████| 72/72 [00:00<00:00, 157.79it/s]


Epoch: [73/100], Loss: 0.28946, Accuracy: 0.872


100%|██████████| 72/72 [00:00<00:00, 155.89it/s]


Epoch: [74/100], Loss: 0.28455, Accuracy: 0.870


100%|██████████| 72/72 [00:00<00:00, 151.48it/s]


Epoch: [75/100], Loss: 0.28149, Accuracy: 0.877


100%|██████████| 72/72 [00:00<00:00, 155.14it/s]


Epoch: [76/100], Loss: 0.27938, Accuracy: 0.875


100%|██████████| 72/72 [00:00<00:00, 154.83it/s]


Epoch: [77/100], Loss: 0.27536, Accuracy: 0.879


100%|██████████| 72/72 [00:00<00:00, 153.51it/s]


Epoch: [78/100], Loss: 0.27556, Accuracy: 0.882


100%|██████████| 72/72 [00:00<00:00, 149.49it/s]


Epoch: [79/100], Loss: 0.27892, Accuracy: 0.878


100%|██████████| 72/72 [00:00<00:00, 155.43it/s]


Epoch: [80/100], Loss: 0.27831, Accuracy: 0.876


100%|██████████| 72/72 [00:00<00:00, 147.60it/s]


Epoch: [81/100], Loss: 0.27606, Accuracy: 0.881


100%|██████████| 72/72 [00:00<00:00, 158.15it/s]


Epoch: [82/100], Loss: 0.27176, Accuracy: 0.881


100%|██████████| 72/72 [00:00<00:00, 152.52it/s]


Epoch: [83/100], Loss: 0.27024, Accuracy: 0.880


100%|██████████| 72/72 [00:00<00:00, 159.12it/s]


Epoch: [84/100], Loss: 0.27101, Accuracy: 0.883


100%|██████████| 72/72 [00:00<00:00, 156.04it/s]


Epoch: [85/100], Loss: 0.26847, Accuracy: 0.884


100%|██████████| 72/72 [00:00<00:00, 155.44it/s]


Epoch: [86/100], Loss: 0.26642, Accuracy: 0.882


100%|██████████| 72/72 [00:00<00:00, 155.96it/s]


Epoch: [87/100], Loss: 0.26413, Accuracy: 0.886


100%|██████████| 72/72 [00:00<00:00, 156.80it/s]


Epoch: [88/100], Loss: 0.26389, Accuracy: 0.883


100%|██████████| 72/72 [00:00<00:00, 152.49it/s]


Epoch: [89/100], Loss: 0.26347, Accuracy: 0.883


100%|██████████| 72/72 [00:00<00:00, 155.59it/s]


Epoch: [90/100], Loss: 0.26233, Accuracy: 0.887


100%|██████████| 72/72 [00:00<00:00, 156.02it/s]


Epoch: [91/100], Loss: 0.26186, Accuracy: 0.885


100%|██████████| 72/72 [00:00<00:00, 142.60it/s]


Epoch: [92/100], Loss: 0.26210, Accuracy: 0.885


100%|██████████| 72/72 [00:00<00:00, 151.87it/s]


Epoch: [93/100], Loss: 0.26373, Accuracy: 0.885


100%|██████████| 72/72 [00:00<00:00, 152.60it/s]


Epoch: [94/100], Loss: 0.25509, Accuracy: 0.891


100%|██████████| 72/72 [00:00<00:00, 149.94it/s]


Epoch: [95/100], Loss: 0.25958, Accuracy: 0.888


100%|██████████| 72/72 [00:00<00:00, 150.16it/s]


Epoch: [96/100], Loss: 0.25953, Accuracy: 0.884


100%|██████████| 72/72 [00:00<00:00, 147.95it/s]


Epoch: [97/100], Loss: 0.26065, Accuracy: 0.889


100%|██████████| 72/72 [00:00<00:00, 152.68it/s]


Epoch: [98/100], Loss: 0.24963, Accuracy: 0.891


100%|██████████| 72/72 [00:00<00:00, 156.80it/s]


Epoch: [99/100], Loss: 0.25264, Accuracy: 0.892


100%|██████████| 72/72 [00:00<00:00, 154.39it/s]

Epoch: [100/100], Loss: 0.25746, Accuracy: 0.887


In [138]:
loss_val = 0.0
acc_val = 0.0
for sample in tqdm(dataloader_test):
    matrix, label = sample[0].to(device), sample[1].to(device)

    # Добавим измерение каналов к данным
    matrix = matrix.unsqueeze(1)
  
    with autocast(use_amp):
        pred = model(matrix)
        loss = loss_fn(pred, label)

    loss_item = loss.item()
    loss_val += loss_item


    acc_current = accuracy(pred.cpu().float(), label.cpu().float())
    acc_val += acc_current


print(f'Loss: {loss_val/len(dataloader_test):.5f}, Accuracy: {acc_val/len(dataloader_test):.3f}')

100%|██████████| 18/18 [00:00<00:00, 428.59it/s]

Loss: 0.86090, Accuracy: 0.788


In [139]:
def aroma_map(matrix):
    matrix = matrix.unsqueeze(1)
    pred = model(matrix).to('cpu')


    df = pd.DataFrame(dict(
        r=torch.sigmoid(pred).detach().numpy()[0],
        theta=['Herbs and spices', 'Tobacco/Smoke', 'Wood', 'Berries', 'Citrus',
       'Fruits ', 'Nuts', 'Coffee', 'Chocolate/Cacao', 'Flowers']))
    
    fig = px.line_polar(df, r='r', theta='theta', line_close=True, template="plotly_dark")
    fig.update_traces(fill='toself', line_color='maroon')
    fig.update_layout(polar=dict(radialaxis=dict(range=[0, 1])))
    fig.show()


In [140]:
aroma_map(X_train[42].to(device).unsqueeze(0))

In [141]:
def aroma_map_comparison(matrix, labels):
    matrix = matrix.unsqueeze(1)
    pred = model(matrix).to('cpu')
    labels = labels.to('cpu')

    print(labels)

    df = pd.DataFrame(dict(
        r=torch.sigmoid(pred).detach().numpy()[0],
        theta=['Herbs and spices', 'Tobacco/Smoke', 'Wood', 'Berries', 'Citrus',
       'Fruits ', 'Nuts', 'Coffee', 'Chocolate/Cacao', 'Flowers']))
    
    df['Label'] = 'Predict'
    
    df1 = pd.DataFrame(dict(
        r=labels.detach().numpy(),
        theta=['Herbs and spices', 'Tobacco/Smoke', 'Wood', 'Berries', 'Citrus',
       'Fruits ', 'Nuts', 'Coffee', 'Chocolate/Cacao', 'Flowers']))
    
    df1['Label'] = 'Experiment'
    
    fig = px.line_polar(pd.concat([df, df1]), color="Label",  r='r', theta='theta', line_close=True, line_shape='linear', color_discrete_sequence=['#008080', '#FFC0CB'],
                    template="plotly_dark")
    

    
    fig.update_traces(fill='toself')
    fig.update_layout(polar=dict(radialaxis=dict(visible=True, range=[0, 1])))
    fig.show()

In [142]:
for i in range(90):
    matrix, label = X_test[i].to(device).unsqueeze(0), y_test[i].to(device)
    aroma_map_comparison(matrix, label)

tensor([0., 0., 0., 0., 1., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([1., 0., 0., 0., 0., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([0., 0., 0., 0., 0., 1., 1., 0., 0., 1.], dtype=torch.float64)


tensor([0., 0., 0., 1., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 1., 1., 0., 0., 0., 0., 1., 0.], dtype=torch.float64)


tensor([1., 0., 0., 1., 1., 0., 0., 0., 1., 0.], dtype=torch.float64)


tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 1., 0., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([0., 1., 0., 1., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 1., 0., 1., 0., 0., 1., 0., 1., 1.], dtype=torch.float64)


tensor([0., 0., 0., 0., 1., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 0., 0., 1., 0., 1.], dtype=torch.float64)


tensor([0., 0., 0., 0., 0., 1., 1., 0., 0., 1.], dtype=torch.float64)


tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([1., 0., 1., 1., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 1., 1., 0., 0., 1., 0., 0., 1., 0.], dtype=torch.float64)


tensor([1., 0., 1., 1., 0., 0., 0., 0., 1., 0.], dtype=torch.float64)


tensor([0., 0., 0., 0., 0., 1., 0., 1., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 0., 0., 1., 0., 0., 1., 0.], dtype=torch.float64)


tensor([1., 0., 1., 1., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 1., 1., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 0., 0., 0., 1., 0., 1., 1., 0.], dtype=torch.float64)


tensor([0., 0., 0., 1., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 1., 0., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 1., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 0., 0., 0., 1., 0.], dtype=torch.float64)


tensor([0., 0., 0., 0., 1., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([1., 0., 0., 0., 1., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([1., 0., 0., 0., 0., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 0., 1., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([0., 0., 0., 0., 0., 1., 1., 0., 0., 1.], dtype=torch.float64)


tensor([1., 0., 0., 0., 0., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([1., 0., 0., 0., 1., 1., 1., 0., 0., 1.], dtype=torch.float64)


tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 1.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 0., 0., 0., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 0., 1., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([1., 0., 0., 0., 0., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([0., 0., 0., 1., 0., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 1., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 0., 0., 1., 1., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 0., 1., 1., 1., 0., 0., 1.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 1., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 0., 1., 1., 0., 0., 1., 0.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 1., 1., 1., 1., 1., 0., 0., 1., 1.], dtype=torch.float64)


tensor([0., 0., 0., 0., 1., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 1., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 1., 1., 0., 0., 0., 0., 1., 0.], dtype=torch.float64)


tensor([1., 1., 1., 1., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([0., 0., 0., 0., 1., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([1., 1., 1., 0., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 1., 0., 0., 1., 1.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 1., 1., 0., 0., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([1., 1., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 1., 1., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 1., 1., 1., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([1., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 0., 0., 1., 1., 0., 0., 1.], dtype=torch.float64)


tensor([1., 0., 0., 1., 1., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 1., 0., 0., 1., 0.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 0., 0., 0., 0., 1.], dtype=torch.float64)


tensor([1., 0., 0., 0., 1., 1., 0., 0., 0., 1.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 1., 1., 0., 0., 1.], dtype=torch.float64)


tensor([1., 0., 0., 1., 0., 0., 0., 0., 0., 1.], dtype=torch.float64)


tensor([1., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=torch.float64)


tensor([0., 0., 0., 0., 1., 1., 0., 0., 0., 0.], dtype=torch.float64)
